import { JokerData } from "../JokerCard";
import JSZip from "jszip";
import { addAtlasToZip } from "./ImageProcessor";
import {
  generateJokerBaseCode,
  generateBasicLocVarsFunction,
} from "./JokerBase";
import { generatePokerHandCondition } from "./effects/PokerHandEffects";
import { generateCalculateFunction } from "./calculateUtils";
import { generateSuitCardCondition } from "./effects/SuitCardEffects";

export const exportJokersAsMod = async (
  jokers: JokerData[],
  modName: string,
  authorName: string
): Promise<boolean> => {
  try {
    const zip = new JSZip();
    const modId = modName.toLowerCase().replace(/\s+/g, "");

    zip.file("main.lua", generateMainLua(jokers));
    zip.file(`${modId}.json`, generateModJson(modName, modId, authorName));
    zip.file("config.lua", "return {}");

    await addAtlasToZip(zip, jokers);

    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${modId}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    return true;
  } catch (error) {
    console.error("Failed to generate mod:", error);
    return false;
  }
};

const generateMainLua = (jokers: JokerData[]): string => {
  // Track all helper functions
  const helperFunctions: string[] = [];
  // Track joker-specific data for final generation
  const jokerGenerationData: {
    joker: JokerData;
    index: number;
    functionNames: string[];
  }[] = [];

  // First pass: collect all helper functions
  jokers.forEach((joker, index) => {
    const functionNames: string[] = [];

    if (joker.rules && joker.rules.length > 0) {
      // Check for poker hand rules
      const pokerHandRules = joker.rules.filter((rule) => {
        return rule.conditionGroups.some((group) =>
          group.conditions.some((condition) => condition.type === "hand_type")
        );
      });

      // Generate poker hand condition function if needed
      if (pokerHandRules.length > 0) {
        const pokerHandCondition = generatePokerHandCondition(pokerHandRules);
        if (pokerHandCondition) {
          helperFunctions.push(pokerHandCondition.functionCode);
          functionNames.push(pokerHandCondition.functionName);
        }
      }

      // Check for suit rules
      const suitRules = joker.rules.filter((rule) => {
        return rule.conditionGroups.some((group) =>
          group.conditions.some(
            (condition) =>
              condition.type === "suit_count" || condition.type === "card_suit"
          )
        );
      });

      // Generate suit condition function if needed
      if (suitRules.length > 0) {
        const suitCondition = generateSuitCardCondition(suitRules);
        if (suitCondition) {
          helperFunctions.push(suitCondition.functionCode);
          functionNames.push(suitCondition.functionName);
        }
      }
    }

    // More condition types will be added here in the future

    jokerGenerationData.push({
      joker,
      index,
      functionNames,
    });
  });

  // Start building the output
  let output = `-- FILE GENERATED BY JOKER FORGE

local mod = SMODS.current_mod

mod.config = {}

-- Create custom joker atlas
SMODS.Atlas({
    key = "CustomJokers", 
    path = "CustomJokers.png", 
    px = 71,
    py = 95, 
    atlas_table = "ASSET_ATLAS"
}):register()

`;

  // Add all helper functions first
  if (helperFunctions.length > 0) {
    output += "-- Helper functions for joker conditions\n";
    output += helperFunctions.join("\n\n");
    output += "\n\n";
  }

  // Now add all joker definitions
  jokerGenerationData.forEach(({ joker, index, functionNames }) => {
    output +=
      generateJokerCode(joker, index, "CustomJokers", functionNames) + "\n\n";
  });

  output += "return mod";
  return output;
};

const generateJokerCode = (
  joker: JokerData,
  index: number,
  atlasKey: string,
  conditionFunctions: string[]
): string => {
  console.log(`Generating code for joker: ${joker.name}`);

  // Start with the base joker code
  let jokerCode = generateJokerBaseCode(joker, index, atlasKey);

  // Generate loc_vars function
  const locVarsCode = generateBasicLocVarsFunction(joker);

  // Generate the calculate function that combines all conditions
  const calculateCode = generateCalculateFunction(
    joker,
    joker.rules || [],
    conditionFunctions
  );

  // Add the generated code to the joker
  jokerCode += `,

    ${locVarsCode},

    ${calculateCode}
}`;

  return jokerCode;
};

const generateModJson = (
  modName: string,
  modId: string,
  authorName: string
): string => {
  const metadata = {
    id: modId,
    name: modName,
    display_name: modName,
    author: [authorName],
    description: "Custom jokers created with Joker Forge",
    prefix: modId,
    main_file: "main.lua",
    priority: 1,
    version: "1.0.0",
    dependencies: ["Steamodded (>=1.0.0~BETA-0404a)"],
  };

  return JSON.stringify(metadata, null, 2);
};
