import { JokerData } from "../JokerCard";
import JSZip from "jszip";
import { addAtlasToZip } from "./ImageProcessor";
import {
  generateJokerBaseCode,
  generateBasicLocVarsFunction,
  generateBasicCalculateFunction,
  generateAddToRemoveFromDeckFunctions,
  generateCalcDollarBonusFunction,
  generateSelfDestructCode,
} from "./JokerBase";
import { generatePokerHandCode } from "./effects/PokerHandEffects";
import { generateSuitCardCode } from "./effects/SuitCardEffects";
import { hasEffectType } from "./effectUtils";

export const exportJokersAsMod = async (
  jokers: JokerData[],
  modName: string,
  authorName: string
): Promise<boolean> => {
  try {
    const zip = new JSZip();
    const modId = modName.toLowerCase().replace(/\s+/g, "");

    zip.file("main.lua", generateMainLua(jokers));
    zip.file(`${modId}.json`, generateModJson(modName, modId, authorName));
    zip.file("config.lua", "return {}");

    await addAtlasToZip(zip, jokers);

    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${modId}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    return true;
  } catch (error) {
    console.error("Failed to generate mod:", error);
    return false;
  }
};

const generateMainLua = (jokers: JokerData[]): string => {
  let output = `-- FILE GENERATED BY JOKER FORGE

local mod = SMODS.current_mod

mod.config = {}

-- Create custom joker atlas
SMODS.Atlas({
    key = "CustomJokers", 
    path = "CustomJokers.png", 
    px = 71,
    py = 95, 
    atlas_table = "ASSET_ATLAS"
}):register()

`;

  jokers.forEach((joker, index) => {
    output += generateJokerCode(joker, index, "CustomJokers") + "\n\n";
  });

  output += "return mod";
  return output;
};

const generateJokerCode = (
  joker: JokerData,
  index: number,
  atlasKey: string
): string => {
  console.log(`Generating code for joker: ${joker.name}`);

  // Start with the base joker code
  let jokerCode = generateJokerBaseCode(joker, index, atlasKey);
  const locVarsCode = generateBasicLocVarsFunction(joker);
  let calculateCode = "";
  let addToRemoveFromDeckCode = "";
  let calcDollarBonusCode = "";

  // Check for special effects
  const hasAddDiscard = hasEffectType(joker, "add_discard");
  const hasAddHand = hasEffectType(joker, "add_hand");
  const hasAddMoney = hasEffectType(joker, "add_money");
  const hasSelfDestruct = hasEffectType(joker, "destroy_self");

  // Generate the appropriate special functions
  if (hasAddDiscard || hasAddHand) {
    addToRemoveFromDeckCode = generateAddToRemoveFromDeckFunctions(joker);
  }

  if (hasAddMoney) {
    calcDollarBonusCode = generateCalcDollarBonusFunction(joker);
  }

  if (hasSelfDestruct) {
    // Self-destruct overrides normal calculate
    calculateCode = generateSelfDestructCode(joker);
  } else if (joker.rules && joker.rules.length > 0) {
    // Normal rules-based code generation
    const suitRules = joker.rules.filter((rule) => {
      return rule.conditionGroups.some((group) =>
        group.conditions.some((condition) => condition.type === "card_suit")
      );
    });

    const pokerHandRules =
      suitRules.length === 0
        ? joker.rules.filter((rule) => rule.trigger === "hand_played")
        : [];

    if (suitRules.length > 0) {
      calculateCode = generateSuitCardCode(joker, suitRules);

      if (!calculateCode || calculateCode.trim() === "") {
        calculateCode = generateBasicCalculateFunction(joker);
      }
    } else if (pokerHandRules.length > 0) {
      calculateCode = generatePokerHandCode(joker, pokerHandRules);

      if (!calculateCode || calculateCode.trim() === "") {
        calculateCode = generateBasicCalculateFunction(joker);
      }
    } else {
      calculateCode = generateBasicCalculateFunction(joker);
    }
  } else {
    // Default calculate for basic effects
    calculateCode = generateBasicCalculateFunction(joker);
  }

  // Add all the generated code to the joker definition
  jokerCode += `,

    ${locVarsCode}${calcDollarBonusCode}${addToRemoveFromDeckCode},

    ${calculateCode}
}`;

  return jokerCode;
};

const generateModJson = (
  modName: string,
  modId: string,
  authorName: string
): string => {
  const metadata = {
    id: modId,
    name: modName,
    display_name: modName,
    author: [authorName],
    description: "Custom jokers created with Joker Forge",
    prefix: modId,
    main_file: "main.lua",
    priority: 1,
    version: "1.0.0",
    dependencies: ["Steamodded (>=1.0.0~BETA-0404a)"],
  };

  return JSON.stringify(metadata, null, 2);
};
